# Simple data transformation workflow
name: ARM Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch

jobs:
  arminstall:
    runs-on: ubuntu-24.04-arm
    container: devxygmbh/r-alpine:4-3.21
    steps:      
      - run: |
          R -e 'install.packages("pak")'
          R -e 'pak::pak("data.table")'
          R -e 'pak::pak("gert")'
          R -e 'pak::pak("remotes")'
